"""Wire dialects: Anthropic Messages, OpenAI-compatible Chat Completions, and the OpenAI
Responses API (stateless use, as Codex CLI sends it).

Each dialect parses a request body into a NormRequest, builds replay responses
(JSON or SSE) from tool calls, extracts calls/usage from upstream responses
(JSON or SSE, incrementally), and inserts frontier hints (`inject_hint`, at the end of the
history or, for a hint that is re-inserted, at the message it was first given after; see
compaction.sticky_hints).
"""

from __future__ import annotations

import json
import re
import time
from typing import Any

from .model import REPLAY_MARK, USER, Episode, NormRequest, Observation, ResponseInfo, Step, ToolCall, Usage, calls_sig
from .util import h, rand_id, strip_reminders


def _text_of(content: Any) -> str:
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    out = []
    for block in content:
        if isinstance(block, str):
            out.append(block)
        elif isinstance(block, dict):
            t = block.get("type")
            if t in ("text", "input_text", "output_text") or (t is None and "text" in block):
                out.append(block.get("text", ""))
            elif t in ("image", "image_url", "input_image"):
                out.append("[image]")
            elif t == "tool_result":
                out.append(_text_of(block.get("content")))
            elif t == "document":
                out.append("[document]")
    return "\n".join(x for x in out if x)


def _sse(event: str | None, data: Any) -> bytes:
    payload = data if isinstance(data, str) else json.dumps(data, separators=(",", ":"))
    head = f"event: {event}\n" if event else ""
    return f"{head}data: {payload}\n\n".encode()


# Anthropic models by how `thinking` behaves (model ids may carry a platform prefix such as
# `anthropic.` or `us.anthropic.`, hence `search`):
#   thinking_default_on: omitting `thinking` still runs adaptive thinking (Fable, Mythos, Opus 5,
#       Opus 5.5, Sonnet 5, and later generations), so removing the parameter does not turn it off;
#   thinking_always_on: `{"type": "disabled"}` is a 400 as well (Fable, Mythos, Opus 5.5 and later).
_THINK_DEFAULT_ON = re.compile(r"claude-(?:fable|mythos|opus-(?:[5-9]|\d\d)|sonnet-(?:[5-9]|\d\d))(?:[-.@_]|$)")
_THINK_ALWAYS_ON = re.compile(r"claude-(?:fable|mythos|opus-5-(?:[5-9]|\d\d)|opus-(?:[6-9]|\d\d))(?:[-.@_]|$)")


def thinking_default_on(model: str) -> bool:
    return bool(_THINK_DEFAULT_ON.search(model or ""))


def thinking_always_on(model: str) -> bool:
    return bool(_THINK_ALWAYS_ON.search(model or ""))


# --------------------------------------------------------------------------- episodes
#
# The dialects reduce a conversation to events, then apply the same episode rules:
#   ("u", text, msg_index, with_results)   a user text turn (with_results: text next to tool results)
#   ("a", calls, text)                     an assistant turn
#   ("r", call_id, Observation)            a tool result
#
# Episode modes (config `episode_mode`, per request header `X-TreeJIT-Episode`):
#   auto          a later user turn continues the episode when it is a reply (see episode_of), else it
#                 starts a new task
#   conversation  the whole conversation is one episode (tau-bench style: one task, many user turns)
#   turn          every user text message starts a new episode (the behaviour before multi-turn episodes)

EPISODE_MODES = ("auto", "conversation", "turn")
INTERRUPT_RE = re.compile(r"\[Request interrupted by user[^\]]*\]")
# Claude Code's local slash-command transcript (/model, /cost ...): not part of any task
_LOCAL_CMD_RE = re.compile(
    r"<(command-name|command-message|command-args|local-command-stdout|local-command-stderr)>.*?</\1>"
    r"|Caveat: The messages below were generated by the user while running local commands\.[^\n]*", re.S)
# the agent's turn ended with a request for input: a question (not a generic closer) or a confirmation prompt
_CLOSER_RE = re.compile(r"anything else|something else|any (?:other|more|further) (?:questions?|help|requests?)|"
                        r"further (?:help|assistance|questions?)|(?:help|assist) you with|how (?:can|may) i (?:help|assist)",
                        re.I)
_CONFIRM_RE = re.compile(r"\(yes/no\)|\byes or no\b|\bconfirm|\bshall i\b|\bshould i\b|\bwould you like\b|"
                         r"\bdo you want\b|\bwant me to\b|\bok to proceed\b|\bproceed\?", re.I)
_YES_WORDS = {"yes", "y", "yeah", "yep", "yup", "sure", "ok", "okay", "confirm", "confirmed", "correct", "right",
              "go", "ahead", "proceed", "do", "it", "please", "thanks", "thank", "you", "sounds", "good", "fine", "great",
              "perfect", "absolutely", "of", "course", "definitely", "lgtm", "affirmative", "i", "that's", "thats",
              "is", "with", "the", "that", "this", "all", "looks", "works", "for", "me", "agreed", "agree"}
_NO_WORDS = {"no", "n", "nope", "nah", "don't", "dont", "do", "not", "stop", "wait", "hold", "on", "never", "mind",
             "please", "thanks", "thank", "you", "negative", "now", "it", "that", "this", "i", "changed", "my"}
_YES_START = {"yes", "y", "yeah", "yep", "yup", "sure", "ok", "okay", "confirm", "confirmed", "correct", "go", "proceed",
              "absolutely", "definitely", "lgtm", "affirmative", "please", "sounds", "agreed", "i"}
_NO_START = {"no", "n", "nope", "nah", "don't", "dont", "do", "stop", "wait", "hold", "never", "negative"}
_QUALIFIERS = {"but", "instead", "except", "rather", "actually", "however", "change", "only", "also", "and"}
_NEGATIONS = {"no", "not", "don't", "dont", "never", "nope"}


def clean_user_text(text: str) -> str:
    return _LOCAL_CMD_RE.sub("", strip_reminders(text)).strip()


def reply_kind(text: str) -> str:
    """'yes' / 'no' for a bare confirmation or refusal (at most 2 words beyond the usual phrasing,
    nothing that qualifies it), else 'text'."""
    words = [w.strip(".,!?;:\"'`()*") for w in text.lower().split()]
    words = [w for w in words if w]
    if not words or len(words) > 12 or any(w in _QUALIFIERS for w in words[1:]):
        return "text"
    w0 = words[0]
    if (w0 in _NO_START and sum(1 for w in words if w not in _NO_WORDS) <= 2
            and (w0 != "do" or words[1:2] == ["not"])):
        return "no"
    if any(w in _NEGATIONS for w in words):
        return "text"
    if ((w0 in _YES_START or words[:2] == ["do", "it"]) and sum(1 for w in words if w not in _YES_WORDS) <= 2
            and (w0 != "please" or len(words) > 1) and (w0 != "i" or "confirm" in words)):
        return "yes"
    return "text"


def asks(text: str) -> bool:
    """Did the agent's turn end by asking the user something?"""
    t = text.strip().rstrip("*_`'\" )")
    if not t:
        return False
    tail = t[-300:]
    q = tail.rfind("?")
    if q >= 0 and len(tail) - q <= 200:
        start = max(tail.rfind(c, 0, q) for c in ".!\n") + 1
        if not _CLOSER_RE.search(tail[start : q + 1]):
            return True
    return bool(_CONFIRM_RE.search(tail))


def episode_of(events: list[tuple], mode: str = "auto") -> Episode:
    """The current episode of a conversation, from its events (see above).

    A later user turn (auto mode) continues the episode when
      - it cut in while the agent was working: text next to tool results, an interrupt marker
        (`[Request interrupted by user...]`), or no finished agent turn since the last user turn
        -> a `steer` step;
      - or the agent's turn ended by asking something (a question that isn't a generic closer, or a
        confirmation prompt) -> a `yes` / `no` / `text` step;
      - or it is a bare confirmation or refusal ("yes", "no thanks") even without a question
        -> a `text` step (a `yes` that answered no question is not the confirmation a write may follow).
    Anything else, i.e. a new request after the agent finished without asking, starts a new episode.
    """
    mode = mode if mode in EPISODE_MODES else "auto"
    # merge consecutive user text turns (a local-command transcript or an interrupt marker sent as its
    # own message just before the user's words): one turn
    evs: list[tuple] = []
    for e in events:
        if mode != "turn" and e[0] == "u" and evs and evs[-1][0] == "u":
            p = evs[-1]
            evs[-1] = ("u", (p[1] + "\n" + e[1]).strip(), p[2], p[3] or e[3])
        else:
            evs.append(e)
    bounds: list[int] = []                 # event index of each task boundary
    kinds: dict[int, str] = {}             # event index -> user step kind, for continuation turns
    last_a: tuple | None = None            # the latest assistant turn since the previous user turn
    first_u = True
    for k, e in enumerate(evs):
        if e[0] == "a":
            last_a = e
            continue
        if e[0] != "u":
            continue
        if mode == "turn":
            if not e[3]:
                bounds.append(k)
        elif first_u:
            bounds.append(k)
        elif not clean_user_text(e[1]):
            continue                       # only harness text (reminders, a local command): not a turn
        elif e[3] or INTERRUPT_RE.search(e[1]) or last_a is None or last_a[1]:
            kinds[k] = "steer"             # the user cut in while the agent was working
        else:
            kind = reply_kind(clean_user_text(e[1]))
            asked = asks(last_a[2])
            if mode == "conversation" or kind in ("yes", "no") or asked:
                kinds[k] = kind if asked else "text"
            else:
                bounds.append(k)
        first_u = False
        last_a = None
    start = bounds[-1] if bounds else -1
    if start < 0:
        task = ""
    elif mode == "turn":
        task = strip_reminders(evs[start][1])
    else:
        raw = clean_user_text(evs[start][1])
        task = INTERRUPT_RE.sub("", raw).strip() or raw
    steps: list[Step] = []
    by_id: dict[str, Step] = {}
    for k in range(start + 1, len(evs)):
        e = evs[k]
        if e[0] == "a":
            for c in e[1]:
                st = Step(c)
                steps.append(st)
                by_id[c.id] = st
        elif e[0] == "r":
            st = by_id.get(e[1])
            if st is not None:
                st.obs = e[2]
        elif k in kinds:
            text = INTERRUPT_RE.sub("", clean_user_text(e[1])).strip()
            if text:
                steps.append(Step(ToolCall(f"user_{e[2]}_{h(text, n=8)}", f"{USER}:{kinds[k]}", {}), Observation(text)))
    ep = Episode(task, steps, index=max(0, len(bounds) - 1))
    ep.prior_calls = [c for k in range(0, max(start, 0)) if evs[k][0] == "a" for c in evs[k][1]]
    first = next((e for e in evs if e[0] == "u"), None)
    ep.origin = clean_user_text(first[1]) if first is not None else ""
    for k, e in enumerate(evs):
        if e[0] != "a":
            continue
        ep.anchor_ids = [c.id for c in e[1]]
        ep.anchor_text = " ".join(e[2].split())
        ep.anchor_calls = calls_sig(e[1])
        if e[1]:
            res = next((x for x in evs[k + 1 :] if x[0] == "r" and x[1] == e[1][0].id), None)
            ep.anchor_salt = h(res[2].text, n=12) if res is not None else None
        break
    return ep


class SSEParser:
    """Incremental text/event-stream parser yielding (event, data) pairs."""

    def __init__(self) -> None:
        self._buf = b""

    def feed(self, chunk: bytes) -> list[tuple[str | None, str]]:
        self._buf += chunk.replace(b"\r\n", b"\n")
        events = []
        while b"\n\n" in self._buf:
            raw, self._buf = self._buf.split(b"\n\n", 1)
            event, data = None, []
            for line in raw.decode("utf-8", "replace").split("\n"):
                if line.startswith("event:"):
                    event = line[6:].strip()
                elif line.startswith("data:"):
                    data.append(line[5:].lstrip(" ") if line[5:6] == " " else line[5:])
            if data or event:
                events.append((event, "\n".join(data)))
        return events


class Dialect:
    name = ""
    call_prefix = ""

    def new_call_id(self, node: str, conf: float = 1.0, via: str = "") -> str:
        c = max(0, min(255, round(conf * 255)))
        return f"{self.call_prefix}_{REPLAY_MARK}_{node[:12]}_{c:02x}{rand_id(10)}" + (f"_{via}" if via else "")

    # implemented by subclasses
    def parse_request(self, body: dict, mode: str = "auto") -> NormRequest: ...
    def build_response(self, model: str, calls: list[ToolCall]) -> dict: ...
    def build_sse(self, model: str, calls: list[ToolCall], body: dict) -> list[bytes]: ...
    def parse_response(self, body: dict) -> ResponseInfo: ...
    def stream_accumulator(self) -> "StreamAccumulator": ...
    def inject_hint(self, body: dict, text: str, at: int | None = None) -> dict:
        """`body` with the hint inserted at history item `at` (default: the last one). Returns `body`
        itself (the same object) when the hint can't go there."""
        ...

    def history(self, body: dict) -> list:
        """The conversation items hints are anchored to (messages, or Responses input items)."""
        msgs = body.get("messages")
        return msgs if isinstance(msgs, list) else []

    def prepare_forward(self, req: NormRequest) -> dict:
        return req.raw


class StreamAccumulator:
    def __init__(self) -> None:
        self.parser = SSEParser()
        self.info = ResponseInfo()

    def feed(self, chunk: bytes) -> None:
        for event, data in self.parser.feed(chunk):
            if not data or data == "[DONE]":
                continue
            try:
                obj = json.loads(data)
            except json.JSONDecodeError:
                continue
            self.on_event(event, obj)

    def on_event(self, event: str | None, obj: dict) -> None: ...

    def result(self) -> ResponseInfo:
        return self.info


# --------------------------------------------------------------------------- Anthropic


class Anthropic(Dialect):
    name = "anthropic"
    call_prefix = "toolu"

    def parse_request(self, body: dict, mode: str = "auto") -> NormRequest:
        system = body.get("system") or ""
        system_text = system if isinstance(system, str) else _text_of(system)
        tools = [
            {"name": t.get("name"), "schema": t.get("input_schema"), "description": t.get("description", ""), "type": t.get("type")}
            for t in body.get("tools") or []
            if isinstance(t, dict) and t.get("name")
        ]
        msgs = body.get("messages") or []
        events: list[tuple] = []
        for mi, m in enumerate(msgs):
            if not isinstance(m, dict):
                continue
            content = m.get("content")
            if m.get("role") == "assistant":
                calls, text = [], []
                for b in content if isinstance(content, list) else [content]:
                    if isinstance(b, str):
                        text.append(b)
                    elif isinstance(b, dict) and b.get("type") == "tool_use":
                        calls.append(ToolCall(b.get("id", ""), b.get("name", ""), b.get("input") or {}))
                    elif isinstance(b, dict) and b.get("type") == "text":
                        text.append(b.get("text", ""))
                events.append(("a", calls, "\n".join(text)))
            elif m.get("role") == "user":
                if _has_block(m, "tool_result"):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "tool_result":
                            obs = Observation(_text_of(b.get("content")), bool(b.get("is_error")))
                            events.append(("r", b.get("tool_use_id", ""), obs))
                    extra = "\n".join(b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text")
                    if extra.strip():
                        events.append(("u", extra, mi, True))
                else:
                    events.append(("u", _text_of(content), mi, False))
        ep = episode_of(events, mode)
        ep.ready = bool(msgs) and msgs[-1].get("role") == "user" and all(s.obs is not None for s in ep.steps)
        ep.session = session_of(body)
        thinking = isinstance(body.get("thinking"), dict) and body["thinking"].get("type") in ("enabled", "adaptive")
        return NormRequest(
            "anthropic", body.get("model", ""), system_text, tools, bool(body.get("stream")),
            ep, body, thinking,
        )

    def build_response(self, model: str, calls: list[ToolCall]) -> dict:
        return {
            "id": "msg_" + REPLAY_MARK + rand_id(20),
            "type": "message",
            "role": "assistant",
            "model": model,
            "content": [{"type": "tool_use", "id": c.id, "name": c.name, "input": c.args} for c in calls],
            "stop_reason": "tool_use",
            "stop_sequence": None,
            "usage": {"input_tokens": 0, "output_tokens": 0, "cache_creation_input_tokens": 0, "cache_read_input_tokens": 0},
        }

    def build_sse(self, model: str, calls: list[ToolCall], body: dict) -> list[bytes]:
        msg = self.build_response(model, calls)
        start = dict(msg, content=[], stop_reason=None)
        out = [_sse("message_start", {"type": "message_start", "message": start})]
        for i, c in enumerate(calls):
            out.append(_sse("content_block_start", {"type": "content_block_start", "index": i,
                                                    "content_block": {"type": "tool_use", "id": c.id, "name": c.name, "input": {}}}))
            out.append(_sse("content_block_delta", {"type": "content_block_delta", "index": i,
                                                    "delta": {"type": "input_json_delta", "partial_json": json.dumps(c.args)}}))
            out.append(_sse("content_block_stop", {"type": "content_block_stop", "index": i}))
        out.append(_sse("message_delta", {"type": "message_delta", "delta": {"stop_reason": "tool_use", "stop_sequence": None},
                                          "usage": {"output_tokens": 0}}))
        out.append(_sse("message_stop", {"type": "message_stop"}))
        return out

    def parse_response(self, body: dict) -> ResponseInfo:
        info = ResponseInfo(stop_reason=body.get("stop_reason"))
        for b in body.get("content") or []:
            if b.get("type") == "tool_use":
                info.calls.append(ToolCall(b.get("id", ""), b.get("name", ""), b.get("input") or {}))
            elif b.get("type") == "text":
                info.text += b.get("text", "")
        info.usage = _anthropic_usage(body.get("usage") or {})
        return info

    def stream_accumulator(self) -> StreamAccumulator:
        return _AnthropicStream()

    def inject_hint(self, body: dict, text: str, at: int | None = None) -> dict:
        msgs = body.get("messages") or []
        i = len(msgs) - 1 if at is None else at
        if not 0 <= i < len(msgs) or not isinstance(msgs[i], dict) or msgs[i].get("role") != "user":
            return body
        msg = dict(msgs[i])
        content = msg.get("content")
        blocks = [{"type": "text", "text": content}] if isinstance(content, str) else list(content or [])
        blocks.append({"type": "text", "text": text})
        msg["content"] = blocks
        msgs = list(msgs)
        msgs[i] = msg
        return dict(body, messages=msgs)

    def prepare_forward(self, req: NormRequest) -> dict:
        body = req.raw
        # With extended thinking on, the API expects assistant turns in a tool loop to carry signed
        # thinking blocks. Replayed turns have none, so on models where thinking can be turned off by
        # leaving the parameter out, fall back to a non-thinking frontier call for this episode.
        # On models that think by default (Fable, Mythos, Opus 5 / 5.5, Sonnet 5) leaving it out
        # changes nothing but the cache prefix (and `disabled` is a 400 on the always-thinking ones),
        # so the body goes as it is: replayed turns without thinking blocks are sent unchanged
        # (repro/X2_live_check.py checks the API accepts them).
        if (req.thinking and not thinking_default_on(req.model)
                and any(s.replayed_node for s in req.episode.steps)):
            body = {k: v for k, v in body.items() if k != "thinking"}
        return body


_SESSION_RE = re.compile(r"session[_-]?(?:id)?[\"':=_ -]*([0-9A-Za-z][0-9A-Za-z-]{7,})", re.I)


def session_of(body: dict) -> str:
    """Harness session id from Anthropic `metadata.user_id`. Claude Code sends
    `user_<hash>_account_<uuid>_session_<uuid>`; other builds may send a JSON object with a
    `session_id`. Parsed defensively: anything unrecognised gives no session (derived ids then)."""
    meta = body.get("metadata")
    uid = meta.get("user_id") if isinstance(meta, dict) else None
    if not isinstance(uid, str) or not uid:
        return ""
    if uid.lstrip().startswith("{"):
        try:
            obj = json.loads(uid)
        except ValueError:
            obj = None
        if isinstance(obj, dict):
            sid = obj.get("session_id") or obj.get("sessionId")
            return str(sid)[:200] if sid else ""
    m = _SESSION_RE.search(uid)
    return m.group(1)[:200] if m else ""


def _has_block(msg: dict, kind: str) -> bool:
    c = msg.get("content")
    return isinstance(c, list) and any(isinstance(b, dict) and b.get("type") == kind for b in c)


def _anthropic_usage(u: dict) -> Usage:
    return Usage(
        int(u.get("input_tokens") or 0), int(u.get("output_tokens") or 0),
        int(u.get("cache_read_input_tokens") or 0), int(u.get("cache_creation_input_tokens") or 0),
    )


class _AnthropicStream(StreamAccumulator):
    def __init__(self) -> None:
        super().__init__()
        self._blocks: dict[int, dict] = {}

    def on_event(self, event: str | None, obj: dict) -> None:
        t = obj.get("type")
        if t == "message_start":
            self.info.usage = _anthropic_usage((obj.get("message") or {}).get("usage") or {})
        elif t == "content_block_start":
            self._blocks[obj.get("index", 0)] = dict(obj.get("content_block") or {}, _json="")
        elif t == "content_block_delta":
            b = self._blocks.get(obj.get("index", 0))
            d = obj.get("delta") or {}
            if b is not None:
                if d.get("type") == "input_json_delta":
                    b["_json"] += d.get("partial_json", "")
                elif d.get("type") == "text_delta":
                    self.info.text += d.get("text", "")
        elif t == "content_block_stop":
            b = self._blocks.get(obj.get("index", 0))
            if b is not None and b.get("type") == "tool_use":
                try:
                    args = json.loads(b["_json"]) if b["_json"] else (b.get("input") or {})
                except json.JSONDecodeError:
                    args = {}
                self.info.calls.append(ToolCall(b.get("id", ""), b.get("name", ""), args))
        elif t == "message_delta":
            self.info.stop_reason = (obj.get("delta") or {}).get("stop_reason") or self.info.stop_reason
            u = obj.get("usage") or {}
            if "output_tokens" in u:
                self.info.usage.output_tokens = int(u["output_tokens"] or 0)
            if u.get("input_tokens"):
                self.info.usage.input_tokens = int(u["input_tokens"])


# --------------------------------------------------------------------------- OpenAI


class OpenAI(Dialect):
    name = "openai"
    call_prefix = "call"

    def parse_request(self, body: dict, mode: str = "auto") -> NormRequest:
        msgs = body.get("messages") or []
        system_parts = []
        for m in msgs:
            if m.get("role") in ("system", "developer"):
                system_parts.append(_text_of(m.get("content")))
            else:
                break
        tools = []
        for t in body.get("tools") or []:
            fn = t.get("function") if isinstance(t, dict) else None
            if fn and fn.get("name"):
                tools.append({"name": fn["name"], "schema": fn.get("parameters"), "description": fn.get("description", "")})
        events: list[tuple] = []
        for mi, m in enumerate(msgs):
            if not isinstance(m, dict):
                continue
            role = m.get("role")
            if role == "assistant":
                calls = []
                for tc in m.get("tool_calls") or []:
                    fn = tc.get("function") or {}
                    raw = fn.get("arguments") or "{}"
                    try:
                        args = json.loads(raw) if isinstance(raw, str) else dict(raw)
                    except json.JSONDecodeError:
                        args = {"_raw": raw}
                    if not isinstance(args, dict):
                        args = {"_value": args}
                    calls.append(ToolCall(tc.get("id", ""), fn.get("name", ""), args))
                events.append(("a", calls, _text_of(m.get("content"))))
            elif role == "tool":
                events.append(("r", m.get("tool_call_id", ""), Observation(_text_of(m.get("content")), False)))
            elif role == "user":
                events.append(("u", _text_of(m.get("content")), mi, False))
        ep = episode_of(events, mode)
        ep.ready = bool(msgs) and msgs[-1].get("role") in ("tool", "user") and all(s.obs is not None for s in ep.steps)
        # prompt_cache_key: harnesses such as Codex set it per conversation; `user` / `safety_identifier`
        # name an end user, so they only add to the derived key (see engine.TreeJIT._conv_key)
        ep.session = str(body.get("prompt_cache_key") or "")[:200]
        ep.user = str(body.get("user") or body.get("safety_identifier") or "")[:200]
        return NormRequest("openai", body.get("model", ""), "\n".join(system_parts), tools, bool(body.get("stream")),
                           ep, body)

    def build_response(self, model: str, calls: list[ToolCall]) -> dict:
        return {
            "id": "chatcmpl-" + REPLAY_MARK + rand_id(20),
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model,
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": None, "tool_calls": [
                    {"id": c.id, "type": "function", "function": {"name": c.name, "arguments": json.dumps(c.args)}} for c in calls
                ]},
                "finish_reason": "tool_calls",
            }],
            "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
        }

    def build_sse(self, model: str, calls: list[ToolCall], body: dict) -> list[bytes]:
        cid, created = "chatcmpl-" + REPLAY_MARK + rand_id(20), int(time.time())

        def chunk(delta: dict, finish: str | None = None) -> bytes:
            return _sse(None, {"id": cid, "object": "chat.completion.chunk", "created": created, "model": model,
                               "choices": [{"index": 0, "delta": delta, "finish_reason": finish}]})

        out = [chunk({"role": "assistant", "content": None})]
        for i, c in enumerate(calls):
            out.append(chunk({"tool_calls": [{"index": i, "id": c.id, "type": "function", "function": {"name": c.name, "arguments": ""}}]}))
            out.append(chunk({"tool_calls": [{"index": i, "function": {"arguments": json.dumps(c.args)}}]}))
        out.append(chunk({}, "tool_calls"))
        if (body.get("stream_options") or {}).get("include_usage"):
            out.append(_sse(None, {"id": cid, "object": "chat.completion.chunk", "created": created, "model": model, "choices": [],
                                   "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}}))
        out.append(b"data: [DONE]\n\n")
        return out

    def parse_response(self, body: dict) -> ResponseInfo:
        info = ResponseInfo()
        choices = body.get("choices") or [{}]
        msg = choices[0].get("message") or {}
        info.stop_reason = choices[0].get("finish_reason")
        info.text = msg.get("content") or ""
        for tc in msg.get("tool_calls") or []:
            fn = tc.get("function") or {}
            try:
                args = json.loads(fn.get("arguments") or "{}")
            except json.JSONDecodeError:
                args = {}
            info.calls.append(ToolCall(tc.get("id", ""), fn.get("name", ""), args if isinstance(args, dict) else {}))
        info.usage = _openai_usage(body.get("usage") or {})
        return info

    def stream_accumulator(self) -> StreamAccumulator:
        return _OpenAIStream()

    def inject_hint(self, body: dict, text: str, at: int | None = None) -> dict:
        msgs = body.get("messages") or []
        i = len(msgs) - 1 if at is None else at
        if not 0 <= i < len(msgs) or not isinstance(msgs[i], dict):
            return body
        msg = dict(msgs[i])
        c = msg.get("content")
        if isinstance(c, list):
            msg["content"] = list(c) + [{"type": "text", "text": text}]
        else:
            msg["content"] = (c or "") + "\n\n" + text
        msgs = list(msgs)
        msgs[i] = msg
        return dict(body, messages=msgs)


def _openai_usage(u: dict) -> Usage:
    cached = int(((u.get("prompt_tokens_details") or {}).get("cached_tokens")) or 0)
    return Usage(int(u.get("prompt_tokens") or 0) - cached, int(u.get("completion_tokens") or 0), cached, 0)


class _OpenAIStream(StreamAccumulator):
    def __init__(self) -> None:
        super().__init__()
        self._calls: dict[int, dict] = {}

    def on_event(self, event: str | None, obj: dict) -> None:
        if obj.get("usage"):
            self.info.usage = _openai_usage(obj["usage"])
        for ch in obj.get("choices") or []:
            d = ch.get("delta") or {}
            if d.get("content"):
                self.info.text += d["content"]
            for tc in d.get("tool_calls") or []:
                slot = self._calls.setdefault(tc.get("index", 0), {"id": "", "name": "", "args": ""})
                slot["id"] = tc.get("id") or slot["id"]
                fn = tc.get("function") or {}
                slot["name"] = fn.get("name") or slot["name"]
                slot["args"] += fn.get("arguments") or ""
            if ch.get("finish_reason"):
                self.info.stop_reason = ch["finish_reason"]

    def result(self) -> ResponseInfo:
        self.info.calls = []
        for _, c in sorted(self._calls.items()):
            try:
                args = json.loads(c["args"]) if c["args"] else {}
            except json.JSONDecodeError:
                args = {}
            self.info.calls.append(ToolCall(c["id"], c["name"], args if isinstance(args, dict) else {}))
        return self.info


# --------------------------------------------------------------------------- OpenAI Responses
#
# POST /v1/responses as a stateless client sends it (Codex CLI: `store: false`, the whole conversation in
# `input` on every turn). Input items: messages (`{"role", "content"}`, `type: "message"` optional),
# `function_call {id, call_id, name, arguments}` paired with `function_call_output {call_id, output}` on
# call_id, `reasoning` items (kept as they are), and parsed-but-rarely-replayed `custom_tool_call {call_id,
# name, input}` (args `{"$input": text}`) and `local_shell_call {call_id, action}` (tool `local_shell`,
# args = the exec action without its type). Replayed calls carry the treejit id in `call_id`
# (`call_tj_<node>_...`); the item `id` is `fc_tj...` and is stripped before a forward (see prepare_forward).
#
# Stateful requests (phase 1): `previous_response_id` (server-side chaining: `input` holds only the new
# items) or `conversation` pass through untouched and unrecorded (tier `pass`, note `stateful`). A replayed
# response id (`resp_tj...`) is unknown upstream, so treejit never answers a stateful conversation.

CUSTOM_INPUT = "$input"                    # the single argument of a custom (freeform) tool call
_CODEX_WRAPPERS = re.compile(r"<(environment_context|user_instructions|user_shell_command)>.*?</\1>", re.S)
_CALL_ITEMS = ("function_call", "custom_tool_call", "local_shell_call")
_OUTPUT_ITEMS = ("function_call_output", "custom_tool_call_output", "local_shell_call_output")


def _responses_input(body: dict) -> list:
    inp = body.get("input")
    if isinstance(inp, str):
        return [{"role": "user", "content": inp}]
    return inp if isinstance(inp, list) else []


def _item_type(item: dict) -> str:
    return item.get("type") or ("message" if "role" in item else "")


def _args_of(raw: Any) -> dict:
    try:
        args = json.loads(raw) if isinstance(raw, str) else (dict(raw) if isinstance(raw, dict) else {})
    except (json.JSONDecodeError, ValueError):
        return {"_raw": raw}
    return args if isinstance(args, dict) else {"_value": args}


def _call_of(item: dict) -> ToolCall | None:
    t = _item_type(item)
    cid = item.get("call_id") or item.get("id") or ""
    if t == "function_call":
        return ToolCall(cid, item.get("name", ""), _args_of(item.get("arguments")))
    if t == "custom_tool_call":
        return ToolCall(cid, item.get("name", ""), {CUSTOM_INPUT: item.get("input", "")})
    if t == "local_shell_call":
        action = {k: v for k, v in (item.get("action") or {}).items() if k != "type"}
        return ToolCall(cid, "local_shell", action)
    return None


def _call_item(c: ToolCall) -> dict:
    rid = REPLAY_MARK + rand_id(20)
    if set(c.args) == {CUSTOM_INPUT}:
        return {"type": "custom_tool_call", "id": "ctc_" + rid, "call_id": c.id, "name": c.name,
                "input": str(c.args[CUSTOM_INPUT]), "status": "completed"}
    if c.name == "local_shell":
        return {"type": "local_shell_call", "id": "lsc_" + rid, "call_id": c.id, "status": "completed",
                "action": dict(c.args, type="exec")}
    return {"type": "function_call", "id": "fc_" + rid, "call_id": c.id, "name": c.name,
            "arguments": json.dumps(c.args), "status": "completed"}


def _responses_usage(u: dict) -> Usage:
    cached = int(((u.get("input_tokens_details") or {}).get("cached_tokens")) or 0)
    return Usage(int(u.get("input_tokens") or 0) - cached, int(u.get("output_tokens") or 0), cached, 0)


def _responses_stop(resp: dict, calls: list, refused: bool = False) -> str:
    """A Chat-Completions-style stop reason: an unfinished response maps to one engine.TRUNCATED knows."""
    if (resp.get("status") or "completed") != "completed":
        reason = (resp.get("incomplete_details") or {}).get("reason") or ""
        return "content_filter" if reason == "content_filter" else "length"
    if refused:
        return "refusal"
    return "tool_calls" if calls else "stop"


def _message_text(item: dict) -> tuple[str, bool]:
    text, refused = [], False
    for part in item.get("content") or []:
        if isinstance(part, dict):
            if part.get("type") in ("output_text", "text"):
                text.append(part.get("text", ""))
            elif part.get("type") == "refusal":
                refused = True
    return "".join(text), refused


class Responses(Dialect):
    name = "responses"
    call_prefix = "call"

    def history(self, body: dict) -> list:
        return _responses_input(body)

    def parse_request(self, body: dict, mode: str = "auto") -> NormRequest:
        items = _responses_input(body)
        system_parts = [body["instructions"]] if isinstance(body.get("instructions"), str) else []
        k = 0
        while k < len(items) and isinstance(items[k], dict) and items[k].get("role") in ("system", "developer"):
            system_parts.append(_text_of(items[k].get("content")))
            k += 1
        tools = []
        for t in body.get("tools") or []:
            if not isinstance(t, dict):
                continue
            ty = t.get("type", "function")
            if ty == "function" and t.get("name"):
                tools.append({"name": t["name"], "schema": t.get("parameters"), "description": t.get("description", "")})
            elif ty == "custom" and t.get("name"):
                tools.append({"name": t["name"], "schema": {"format": t.get("format")},
                              "description": t.get("description", ""), "type": "custom"})
            elif ty:  # built-in tools (local_shell, web_search, ...): by type
                tools.append({"name": ty, "schema": None, "type": ty})
        stateful = bool(body.get("previous_response_id") or body.get("conversation"))
        events: list = []
        for mi, item in enumerate(items):
            if not isinstance(item, dict) or mi < k:
                continue
            t, role = _item_type(item), item.get("role")
            if t in _CALL_ITEMS or t == "reasoning" or (t == "message" and role == "assistant"):
                # consecutive model-side items (reasoning, text, calls) are one assistant turn
                if not events or not isinstance(events[-1], list):
                    events.append(["a", [], []])
                c = _call_of(item)
                if c is not None:
                    events[-1][1].append(c)
                elif t == "message":
                    events[-1][2].append(_text_of(item.get("content")))
            elif t in _OUTPUT_ITEMS:
                out = item.get("output")
                text = out if isinstance(out, str) else _text_of(out) if isinstance(out, list) else json.dumps(out)
                events.append(("r", item.get("call_id") or item.get("id") or "", Observation(text, False)))
            elif t == "message" and role == "user":
                text = _CODEX_WRAPPERS.sub("", _text_of(item.get("content"))).strip()
                if text:  # Codex's environment/instructions messages are context, not the task
                    events.append(("u", text, mi, False))
        events = [("a", e[1], "\n".join(e[2])) if isinstance(e, list) else e for e in events]
        ep = episode_of(events, mode)
        last = items[-1] if items and isinstance(items[-1], dict) else {}
        ep.ready = (bool(items) and (_item_type(last) in _OUTPUT_ITEMS or last.get("role") == "user")
                    and all(s.obs is not None for s in ep.steps))
        ep.session = str(body.get("prompt_cache_key") or "")[:200]
        ep.user = str(body.get("user") or body.get("safety_identifier") or "")[:200]
        req = NormRequest("responses", body.get("model", ""), "\n".join(p for p in system_parts if p),
                          [] if stateful else tools, bool(body.get("stream")), ep, body)
        if stateful:
            req.passthrough = "stateful"
        return req

    def _response(self, model: str, calls: list[ToolCall]) -> dict:
        return {
            "id": "resp_" + REPLAY_MARK + rand_id(20), "object": "response", "created_at": int(time.time()),
            "status": "completed", "model": model, "output": [_call_item(c) for c in calls],
            "error": None, "incomplete_details": None, "instructions": None, "metadata": {}, "parallel_tool_calls": True,
            "temperature": None, "top_p": None, "tool_choice": "auto", "tools": [],
            "usage": {"input_tokens": 0, "input_tokens_details": {"cached_tokens": 0, "cache_write_tokens": 0}, "output_tokens": 0,
                      "output_tokens_details": {"reasoning_tokens": 0}, "total_tokens": 0},
        }

    def build_response(self, model: str, calls: list[ToolCall]) -> dict:
        return self._response(model, calls)

    def build_sse(self, model: str, calls: list[ToolCall], body: dict) -> list[bytes]:
        resp = self._response(model, calls)
        out: list[bytes] = []

        def ev(kind: str, **data: Any) -> None:
            out.append(_sse(kind, {"type": kind, "sequence_number": len(out), **data}))

        start = dict(resp, status="in_progress", output=[], usage=None)
        ev("response.created", response=start)
        ev("response.in_progress", response=start)
        for i, item in enumerate(resp["output"]):
            if item["type"] == "function_call":
                ev("response.output_item.added", output_index=i, item=dict(item, arguments="", status="in_progress"))
                ev("response.function_call_arguments.delta", item_id=item["id"], output_index=i, delta=item["arguments"])
                ev("response.function_call_arguments.done", item_id=item["id"], output_index=i, arguments=item["arguments"])
            elif item["type"] == "custom_tool_call":
                ev("response.output_item.added", output_index=i, item=dict(item, input="", status="in_progress"))
                ev("response.custom_tool_call_input.delta", item_id=item["id"], output_index=i, delta=item["input"])
                ev("response.custom_tool_call_input.done", item_id=item["id"], output_index=i, input=item["input"])
            else:
                ev("response.output_item.added", output_index=i, item=dict(item, status="in_progress"))
            ev("response.output_item.done", output_index=i, item=item)
        ev("response.completed", response=resp)
        return out

    def parse_response(self, body: dict) -> ResponseInfo:
        info = ResponseInfo()
        refused = False
        for item in body.get("output") or []:
            if not isinstance(item, dict):
                continue
            c = _call_of(item)
            if c is not None:
                info.calls.append(c)
            elif _item_type(item) == "message":
                text, r = _message_text(item)
                info.text += text
                refused = refused or r
        info.stop_reason = _responses_stop(body, info.calls, refused)
        info.usage = _responses_usage(body.get("usage") or {})
        return info

    def stream_accumulator(self) -> StreamAccumulator:
        return _ResponsesStream()

    def inject_hint(self, body: dict, text: str, at: int | None = None) -> dict:
        """A hint is its own user message item, inserted after item `at` (default: at the end)."""
        items = _responses_input(body)
        i = len(items) - 1 if at is None else at
        if not 0 <= i < len(items):
            return body
        items = list(items)
        items.insert(i + 1, {"type": "message", "role": "user", "content": [{"type": "input_text", "text": text}]})
        return dict(body, input=items)

    def prepare_forward(self, req: NormRequest) -> dict:
        """Replayed call items carry an item id (`fc_tj...`) the server never issued. Item ids are
        optional on input, and whether the API accepts an unknown one is unverified (with `store: true` it
        may try to resolve it, and reasoning models pair a function_call id with its reasoning item), so
        the id is dropped from every replayed item; `call_id`, which pairs the output, stays."""
        body = req.raw
        items = body.get("input")
        if req.passthrough or not isinstance(items, list):
            return body
        out, changed = [], False
        for item in items:
            if (isinstance(item, dict) and _item_type(item) in _CALL_ITEMS and "id" in item
                    and Step(ToolCall(str(item.get("call_id") or ""), "", {})).replayed_node):
                item = {k: v for k, v in item.items() if k != "id"}
                changed = True
            out.append(item)
        return dict(body, input=out) if changed else body


class _ResponsesStream(StreamAccumulator):
    def __init__(self) -> None:
        super().__init__()
        self._items: dict[int, dict] = {}
        self._args: dict[int, str] = {}
        self._done: dict[int, dict] = {}
        self._resp: dict | None = None
        self._refused = False

    def on_event(self, event: str | None, obj: dict) -> None:
        t = obj.get("type") or event or ""
        i = obj.get("output_index", 0)
        if t == "response.output_item.added":
            self._items[i] = dict(obj.get("item") or {})
        elif t in ("response.function_call_arguments.delta", "response.custom_tool_call_input.delta"):
            self._args[i] = self._args.get(i, "") + (obj.get("delta") or "")
        elif t == "response.output_item.done":
            self._done[i] = dict(obj.get("item") or {})
        elif t == "response.output_text.delta":
            self.info.text += obj.get("delta") or ""
        elif t == "response.refusal.delta":
            self._refused = True
        elif t in ("response.completed", "response.incomplete", "response.failed"):
            self._resp = obj.get("response") or {}
            self.info.usage = _responses_usage(self._resp.get("usage") or {})
            self.info.stop_reason = _responses_stop(self._resp, [None] if self._items else [], self._refused)

    def result(self) -> ResponseInfo:
        self.info.calls = []
        for i in sorted(set(self._items) | set(self._done)):
            item = self._done.get(i)
            if item is None:  # the stream ended before the item was done: use what arrived
                item = dict(self._items[i])
                if _item_type(item) == "function_call":
                    item["arguments"] = self._args.get(i, "")
                elif _item_type(item) == "custom_tool_call":
                    item["input"] = self._args.get(i, "")
            c = _call_of(item)
            if c is not None:
                self.info.calls.append(c)
        if not self.info.calls and self._resp is not None:
            self.info.calls = [c for c in (_call_of(x) for x in self._resp.get("output") or [] if isinstance(x, dict))
                               if c is not None]
        if self._resp is not None:
            self.info.stop_reason = _responses_stop(self._resp, self.info.calls, self._refused)
        return self.info


DIALECTS: dict[str, Dialect] = {"anthropic": Anthropic(), "openai": OpenAI(), "responses": Responses()}


def get(name: str) -> Dialect:
    return DIALECTS[name]
